services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_POSTGRES_USER: user
      APP_POSTGRES_PASSWORD: password
      APP_POSTGRES_HOST: todo_db
      APP_POSTGRES_PORT: 5432
      APP_POSTGRES_DB: todo
  db:
    image: postgres:latest
    container_name: todo_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d todo"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
